### ISSUE TITLE
Missed /number/1/query API

### ISSUE THREAD

**Issue by olegshtch** [infobip/infobip-api-java-client#16]
2.2.0 version has `NumberContextQuery` which queries path `/number/1/query`. New versions doesn't have such API.

**Comment by kiselica-aldin** [comment]
Hello @olegshtch 
That is true.

The CHANGELOG `Removed` section for Java lib was not written perfectly and missed several endpoints which were not directly related to OMNI (which was the only stated removed API set).

In case you really need that endpoint, and you already switched to 3.x.x I suggest calling it directly as documented [HERE](https://www.infobip.com/docs/api#platform-connectivity/number-lookup/number-context-lookup).

In case you did not upgraded already then feel free to use 2.x.x for a while since we do plan to introduce those (and many other) endpoints in future iterations.
