### ISSUE TITLE
Error mapping Response type UTILITY on enum  com.infobip.model.WhatsAppCategory

### ISSUE THREAD

**Issue by gcorroto** [infobip/infobip-api-java-client#36]
Hi, we are having an issue trying to read the Infobip WhatsApp templates.

There was an error when reading the response body. Infobip API responded with status code 200 upon calling GET /whatsapp/2/senders/XXXXXXXXX/templates. This can happen due to a response timeout, networking issues or an invalid deserialization definition. Check the exception's root cause for more details. If you are having trouble interpreting the error, contact support@infobip.com or open an issue on our Github repo.Include all details you find relevant. Thank you for using our library!

java.lang.IllegalArgumentException: Unexpected enum value 'UTILITY'.
        at com.infobip.model.WhatsAppCategory.fromValue(WhatsAppCategory.java:57) ~[infobip-api-java-client-4.0.0.jar:na]
        at jdk.internal.reflect.GeneratedMethodAccessor154.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]

**Comment by gcorroto** [comment]
I think the solution would be this. All the best.

![image](https://github.com/infobip/infobip-api-java-client/assets/67109078/965aeac0-f168-4ce5-9185-2ee391ed0c26)

**Comment by ib-tjuhasz** [comment]
Hi @mmufa, @evan1026 ,

Thank you for bringing the issue to our attention! We appreciate your diligence in reporting it. Your feedback is crucial in helping us maintain and improve the project.

We're pleased to inform you that the issue has been addressed and fixed in the latest release [4.1.0](https://github.com/infobip/infobip-api-java-client/releases/tag/4.1.0).

If you have any more feedback, encounter additional issues, or have further questions, please don't hesitate to let us know. 

Best regards,
Tamás Juhász
