### ISSUE TITLE
Template Id cannot be cast to Integer

### ISSUE THREAD

**Issue by mmufa** [infobip/infobip-api-java-client#37]
Version  v4.0.0 and 

When i generate broadcast template in dashboard I get templateId that is greater then 2147483647. 

sendEmail() method accepts templateId as Integer so we can never send that template if generated id is greater then max value for Integer.

Current workaround is to use REST API not SDK. We can send it as a String then.

Recreation:
1. Generate new template inside Dashboard and make sure that generated template id is greater then 2147483647
2. Try to cast it to integer 
3. It will fail with error that it is not able to cast it since it is too big

Suggestion:
Make templateId as a String. If I use REST API I can send it as a String and it works properly.

**Comment by evan1026** [comment]
The REST API says that templateId is a 64-bit integer, so changing the SDK to use a Long instead of an Integer should get it in sync with the API

**Comment by ib-tjuhasz** [comment]
Hi @mmufa, @evan1026 ,

Thank you for bringing the issue to our attention! We appreciate your diligence in reporting it. Your feedback is crucial in helping us maintain and improve the project.

We're pleased to inform you that the issue has been addressed and fixed in the latest release [4.1.0](https://github.com/infobip/infobip-api-java-client/releases/tag/4.1.0).

If you have any more feedback, encounter additional issues, or have further questions, please don't hesitate to let us know. 

Best regards,
Tamás Juhász
